sudo: required
services:
  - docker
before_install:
  - docker build -t guilhermeduane/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true guilhermeduane/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: docker-react
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY